def comment_to_html(comment: str) -> str:
    return f"""
    <html>
    <head>
        <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600;700&family=DM+Sans:wght@300;400;500&display=swap" rel="stylesheet">
        <style>
            * {{ box-sizing: border-box; margin: 0; padding: 0; }}

            body {{
                font-family: 'DM Sans', sans-serif;
                font-weight: 300;
                background: #f7f5f0;
                color: #1a1a2e;
                display: flex;
                justify-content: center;
                align-items: flex-start;
                padding: 40px 20px;
                min-height: 100vh;
            }}

            .card {{
                background: white;
                border-radius: 16px;
                padding: 40px 48px;
                max-width: 780px;
                width: 100%;
                box-shadow: 0 4px 40px rgba(0,0,0,0.07);
                border-top: 5px solid #00C896;
                animation: fadeUp 0.6s ease forwards;
                opacity: 0;
                transform: translateY(20px);
            }}

            @keyframes fadeUp {{
                to {{ opacity: 1; transform: translateY(0); }}
            }}

            .header {{
                display: flex;
                align-items: center;
                gap: 14px;
                margin-bottom: 28px;
            }}

            .icon {{
                background: #e6fff8;
                color: #00C896;
                font-size: 1.4em;
                width: 48px;
                height: 48px;
                border-radius: 12px;
                display: flex;
                align-items: center;
                justify-content: center;
                flex-shrink: 0;
            }}

            .header-text h2 {{
                font-family: 'Playfair Display', serif;
                font-size: 1.4em;
                color: #1a1a2e;
                margin-bottom: 2px;
            }}

            .header-text span {{
                font-size: 0.78em;
                color: #999;
                letter-spacing: 0.5px;
                text-transform: uppercase;
            }}

            .divider {{
                height: 1px;
                background: linear-gradient(to right, #00C896, transparent);
                margin-bottom: 28px;
            }}

            .comment {{
                font-size: 0.95em;
                line-height: 1.9;
                color: #444;
                font-weight: 300;
            }}

            .comment::first-letter {{
                font-family: 'Playfair Display', serif;
                font-size: 2.2em;
                font-weight: 700;
                color: #00C896;
                float: left;
                line-height: 0.8;
                margin-right: 6px;
                margin-top: 4px;
            }}

            .footer {{
                margin-top: 32px;
                padding-top: 16px;
                border-top: 1px solid #f0f0f0;
                display: flex;
                align-items: center;
                gap: 8px;
                font-size: 0.75em;
                color: #bbb;
            }}

            .dot {{
                width: 6px;
                height: 6px;
                background: #00C896;
                border-radius: 50%;
            }}
        </style>
    </head>
    <body>
        <div class="card">
            <div class="header">
                <div class="icon">💡</div>
                <div class="header-text">
                    <h2>What Was Improved</h2>
                    <span>SEO & AEO Analysis by Claude</span>
                </div>
            </div>
            <div class="divider"></div>
            <div class="comment">{comment}</div>
            <div class="footer">
                <div class="dot"></div>
                Generated by Claude · 4IP Group SEO Optimizer
            </div>
        </div>
    </body>
    </html>
    """